# Generated by Django 4.0.1 on 2022-01-13 20:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=300)),
                ('customer_last_name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 1, 13, 21, 17, 34, 688145))),
                ('address', models.CharField(max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.TextField(default=' ')),
                ('total_order_price', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 1, 13, 21, 17, 34, 688145))),
                ('order_completed', models.BooleanField(default=False)),
                ('paid_fully', models.BooleanField(default=False)),
                ('deposit', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('counter_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 1, 13, 21, 17, 34, 688145))),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_name', models.CharField(max_length=300)),
                ('price', models.FloatField(default=0)),
                ('last_price_changed_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('buy_price', models.FloatField(default=0)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.order')),
                ('product_ordered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.productsubtype')),
            ],
        ),
    ]
