# Generated by Django 4.0 on 2021-12-31 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_order_date_created_order_order_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.order')),
                ('product_ordered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.productsubtype')),
            ],
        ),
    ]
