# Generated by Django 4.0 on 2022-01-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_order_balance_order_deposit_order_discount_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
