# Generated by Django 4.0 on 2022-01-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_suborder_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suborder',
            old_name='total_price',
            new_name='buy_price',
        ),
    ]
