# Generated by Django 4.0.1 on 2022-01-25 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_customer_date_created_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='lower_size',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='suborder',
            name='upper_size',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 30, 18, 970756)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 30, 18, 972759)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 30, 18, 971761)),
        ),
    ]
