# Generated by Django 4.0 on 2022-01-03 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_rename_total_price_suborder_buy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 16, 45, 50, 827233)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 16, 45, 50, 829234)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 16, 45, 50, 828233)),
        ),
        migrations.AlterField(
            model_name='productsubtype',
            name='last_price_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 16, 45, 50, 829234)),
        ),
    ]
