# Generated by Django 4.0.1 on 2022-01-25 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_suborder_lower_size_suborder_upper_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_description',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 39, 55, 17336)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 39, 55, 19334)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 39, 55, 18335)),
        ),
    ]
