# Generated by Django 4.0 on 2022-01-05 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_costumer_date_created_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 11, 47, 30, 846406)),
        ),
        migrations.AlterField(
            model_name='order',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.costumer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 11, 47, 30, 849407)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 11, 47, 30, 847407)),
        ),
        migrations.AlterField(
            model_name='productsubtype',
            name='last_price_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 11, 47, 30, 848407)),
        ),
    ]
