# Generated by Django 4.0.1 on 2022-01-25 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_remove_order_order_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suborder',
            old_name='lower_size',
            new_name='breadth',
        ),
        migrations.RenameField(
            model_name='suborder',
            old_name='upper_size',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 50, 39, 926619)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 50, 39, 926619)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 17, 50, 39, 926619)),
        ),
    ]
