# Generated by Django 4.0 on 2022-01-05 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_costumer_date_created_alter_order_costumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costumer',
            name='costumer_last_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costumer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 19, 46, 31, 969661)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 19, 46, 31, 971661)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 19, 46, 31, 970659)),
        ),
        migrations.AlterField(
            model_name='productsubtype',
            name='last_price_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 19, 46, 31, 970659)),
        ),
    ]
