# Generated by Django 4.0.1 on 2022-01-25 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_rename_lower_size_suborder_breadth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='sub_order_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 18, 40, 29, 589286)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 18, 40, 29, 589286)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 18, 40, 29, 589286)),
        ),
    ]
