# Generated by Django 4.0.1 on 2022-01-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_costumer_address_alter_costumer_costumer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 21, 55, 30, 387643)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 21, 55, 30, 395643)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 21, 55, 30, 387643)),
        ),
        migrations.AlterField(
            model_name='productsubtype',
            name='last_price_changed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 21, 55, 30, 395643)),
        ),
    ]
