# Generated by Django 4.0.1 on 2022-01-25 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_suborder_sub_order_total_alter_customer_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_first_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_last_name',
            new_name='customer_full_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 19, 12, 49, 446261)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 19, 12, 49, 447261)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 19, 12, 49, 446261)),
        ),
    ]
