# Generated by Django 4.0.1 on 2022-01-10 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_costumer_date_created_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 16, 36, 31, 452927)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 16, 36, 31, 453926)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 16, 36, 31, 452927)),
        ),
        migrations.AlterField(
            model_name='productsubtype',
            name='last_price_changed_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
