# Generated by Django 4.0.1 on 2022-02-22 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_rename_customer_first_name_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 15, 51, 13, 502924)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 15, 51, 13, 518546)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 15, 51, 13, 518546)),
        ),
    ]
