# Generated by Django 4.0 on 2021-12-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_applicant',
            new_name='is_student',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_intern',
            new_name='is_teacher',
        ),
    ]
